import {Router} from "express";

export const router = Router()

// PROPOSE MASTER
// VOTE ON MASTER PROPOSAL

// PROPOSE SUBJECT
// VOTE ON SUBJECT PROPOSAL

// GET DESCENDANTS

// UPDATE HELD CREDENTIAL PUBLIC STATUS
// DELETE HELD CREDENTIAL

// ISSUE CREDENTIAL
// REVOKE CREDENTIAL

// CREATE PROOF REQUEST
// DELETE PROOF REQUEST

// RESPOND TO PROOF REQUEST
