#!/bin/bash

cd "$(dirname "$0")" || exit 1
cd ..

if [ "$1" = "build" ]; then
  cd ./temp/aries-cloudagent-python || exit 1
  docker build -t aries-cloudagent-run -f ./docker/Dockerfile.run . || exit 1
  cd ../.. || exit 1
  docker build -t aries_with_node -f ./scripts/aries.Dockerfile .
  docker build -t e_ijaza_app -f ./scripts/Dockerfile .
  docker build -t e_ijaza_app_dev -f ./scripts/dev.Dockerfile .


elif [ "$1" = "rebuild" ]; then
  docker rmi e_ijaza_app
  docker build -t e_ijaza_app -f ./scripts/Dockerfile .


elif [ "$1" = "start" ]; then
  if [ -z "$2" ] || [ -z "$3" ] || [ -z "$4" ]; then
    echo "Usage: $0 $1 [container-name] [app-port] [aries-port] [--dev aries-admin-port]"
    exit 1
  elif [ "$5" = "--dev" ] && [ -n "$6" ]; then
    PORT="$3" docker run -it --rm \
    --name "$2" \
    -p "${3}:${3}" -p "${4}:${4}" -p "${6}:${6}" \
    -e PORT="${3}" \
    -e ARIES_PORT="${4}" \
    -e ARIES_ADMIN_PORT="${6}" \
    -e WEBHOOK_URL="localhost:${3}/webhook" \
    -v "$(pwd):/home/indy/app" \
    -v "$(pwd)/logs/${2}-$(date +"%F-%H-%M-%S"):/home/indy/logs" \
    e_ijaza_app_dev
  else
    ARIES_ADMIN_PORT="10000"
    if [ "$3" = "$ARIES_ADMIN_PORT" ] || [ "$4" = "$ARIES_ADMIN_PORT" ]; then
      echo "Can't use port 10000 as it is used internally to control the aries agent"
      exit 1
    fi
    docker run -itd \
    --name "$2" \
    -p "${3}:${3}" -p "${4}:${4}" \
    -e PORT="${3}" \
    -e ARIES_PORT="${4}" \
    -e ARIES_ADMIN_PORT="${ARIES_ADMIN_PORT}" \
    -e WEBHOOK_URL="localhost:${3}/webhook" \
    -v "$(pwd)/logs/${2}-$(date +"%F-%H-%M-%S"):/home/indy/logs" \
    e_ijaza_app
  fi

elif [ "$1" = "stop" ]; then
  if [ -z "$2" ]; then
    echo "Usage: $0 $1 [container-name]"
    exit 1
  else
    docker stop "$2"
  fi

elif [ "$1" = "remove" ]; then
  if [ -z "$2" ]; then
      echo "Usage: $0 $1 [container-name]"
      exit 1
    else
      docker rm -v "$2"
    fi


else
  echo "Usage: $0 build|rebuild|start|stop"
  exit 1
fi
